const mongoose = require('mongoose');
const dotenv = require('dotenv');
const bcrypt = require('bcryptjs');
const User = require('./models/User');
const Product = require('./models/Product');
const connectDB = require('./config/db');

const path = require('path');
dotenv.config({ path: path.join(__dirname, '.env') });

const importData = async () => {
  try {
    await connectDB();
    await User.deleteMany();
    await Product.deleteMany();

    const salt = await bcrypt.genSalt(10);
    const hashedPassword = await bcrypt.hash('password123', salt);
    
    const adminUser = await User.create({
      name: 'Admin User',
      email: 'admin@homeshop.com',
      password: hashedPassword,
      role: 'admin',
      isVerified: true

    });

    const products = [
        {
            name: "Under Armour Sports Tee",
            description: "Moisture-wicking athletic t-shirt.",
            gender: "Men",
            category: "T-Shirts",
            brand: "Under Armour",
            price: 1899,
            discount: 10,
            stock: 45,
            sizes: ["M", "L", "XL", "XXL"],
            colors: ["Navy Blue", "Black"],
            fabric: "Polyester",
            fit: "Slim",
            imageUrl: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=500&auto=format&fit=crop&q=60",
            ratings: 4.8,
            numReviews: 210
        },
        {
            name: "Reebok Training T-Shirt",
            description: "Lightweight gym t-shirt.",
            gender: "Men",
            category: "T-Shirts",
            brand: "Reebok",
            price: 1099,
            discount: 25,
            stock: 55,
            sizes: ["S", "M", "L"],
            colors: ["Grey", "White"],
            fabric: "Poly Cotton",
            fit: "Regular",
            imageUrl: "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=500&auto=format&fit=crop&q=60",
            ratings: 4.5,
            numReviews: 95
        },
        {
            name: "Tommy Hilfiger Polo",
            description: "Classic collar polo shirt.",
            gender: "Men",
            category: "T-Shirts",
            brand: "Tommy Hilfiger",
            price: 2499,
            discount: 15,
            stock: 25,
            sizes: ["M", "L", "XL"],
            colors: ["Red", "Navy Blue"],
            fabric: "Cotton",
            fit: "Regular",
            imageUrl: "https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=500&auto=format&fit=crop&q=60",
            ratings: 4.7,
            numReviews: 180
        },
        {
            name: "Calvin Klein Basic Tee",
            description: "Minimalist logo t-shirt.",
            gender: "Men",
            category: "T-Shirts",
            brand: "Calvin Klein",
            price: 1999,
            discount: 20,
            stock: 30,
            sizes: ["S", "M", "L", "XL"],
            colors: ["Black", "White"],
            fabric: "Cotton",
            fit: "Slim",
            imageUrl: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=500&auto=format&fit=crop&q=60",
            ratings: 4.6,
            numReviews: 142
        },
        {
            name: "HRX Active T-Shirt",
            description: "Breathable running tee.",
            gender: "Men",
            category: "T-Shirts",
            brand: "HRX",
            price: 699,
            discount: 40,
            stock: 80,
            sizes: ["S", "M", "L", "XL"],
            colors: ["Neon Green", "Black"],
            fabric: "Polyester",
            fit: "Regular",
            imageUrl: "https://images.unsplash.com/photo-1562157873-818bc0726f68?w=500&auto=format&fit=crop&q=60",
            ratings: 4.3,
            numReviews: 320
        },
        {
            name: "U.S. Polo Assn Casual Shirt",
            description: "Checkered cotton casual shirt.",
            gender: "Men",
            category: "Shirts",
            brand: "U.S. Polo Assn",
            price: 1799,
            discount: 30,
            stock: 40,
            sizes: ["M", "L", "XL", "XXL"],
            colors: ["Blue", "Red"],
            fabric: "Cotton",
            fit: "Regular",
            imageUrl: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=500&auto=format&fit=crop&q=60",
            ratings: 4.6,
            numReviews: 115
        },
        {
            name: "Raymond Formal Shirt",
            description: "Crisp formal wear for office.",
            gender: "Men",
            category: "Shirts",
            brand: "Raymond",
            price: 2199,
            discount: 10,
            stock: 35,
            sizes: ["39", "40", "42", "44"],
            colors: ["White", "Light Blue"],
            fabric: "Cotton Blend",
            fit: "Regular",
            imageUrl: "/images/men/raymond_shirt1.jpg",
            imageUrl: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=500&auto=format&fit=crop&q=60",
            ratings: 4.8,
            numReviews: 88
        },
        {
            name: "Arrow Slim Fit Shirt",
            description: "Modern slim fit formal shirt.",
            gender: "Men",
            category: "Shirts",
            brand: "Arrow",
            price: 1899,
            discount: 25,
            stock: 28,
            sizes: ["38", "40", "42"],
            colors: ["Grey"],
            fabric: "Cotton",
            fit: "Slim",
            imageUrl: "https://images.unsplash.com/photo-1620012253295-c15c4215e026?w=500&auto=format&fit=crop&q=60",
            ratings: 4.5,
            numReviews: 67
        },
        {
            name: "Marks & Spencer Linen Shirt",
            description: "Breathable summer linen shirt.",
            gender: "Men",
            category: "Shirts",
            brand: "Marks & Spencer",
            price: 2999,
            discount: 15,
            stock: 20,
            sizes: ["M", "L", "XL"],
            colors: ["Beige", "White"],
            fabric: "Linen",
            fit: "Relaxed",
            imageUrl: "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=500&auto=format&fit=crop&q=60",
            ratings: 4.7,
            numReviews: 54
        },
        {
            name: "Jack & Jones Denim Shirt",
            description: "Rugged casual denim shirt.",
            gender: "Men",
            category: "Shirts",
            brand: "Jack & Jones",
            price: 2299,
            discount: 35,
            stock: 32,
            sizes: ["S", "M", "L", "XL"],
            colors: ["Dark Wash Blue"],
            fabric: "Denim",
            fit: "Slim",
            imageUrl: "https://images.unsplash.com/photo-1588359348347-9bc6cbbb689e?w=500&auto=format&fit=crop&q=60",
            ratings: 4.6,
            numReviews: 198
        },
        {
            name: "Blackberrys Chinos",
            description: "Smart casual chino trousers.",
            gender: "Men",
            category: "Trousers",
            brand: "Blackberrys",
            price: 2499,
            discount: 20,
            stock: 25,
            sizes: ["30", "32", "34", "36"],
            colors: ["Olive", "Khaki"],
            fabric: "Cotton Stretch",
            fit: "Slim",
            imageUrl: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=500&auto=format&fit=crop&q=60",
            ratings: 4.7,
            numReviews: 112
        },
        {
            name: "Dockers Khaki Trousers",
            description: "Classic straight fit khakis.",
            gender: "Men",
            category: "Trousers",
            brand: "Dockers",
            price: 2999,
            discount: 15,
            stock: 18,
            sizes: ["32", "34", "36", "38"],
            colors: ["Beige"],
            fabric: "Cotton",
            fit: "Straight",
            imageUrl: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=500&auto=format&fit=crop&q=60",
            ratings: 4.8,
            numReviews: 89
        },
        {
            name: "UCB Joggers",
            description: "Comfortable fleece joggers.",
            gender: "Men",
            category: "Joggers",
            brand: "United Colors of Benetton",
            price: 1699,
            discount: 30,
            stock: 40,
            sizes: ["S", "M", "L", "XL"],
            colors: ["Navy", "Grey"],
            fabric: "Cotton",
            fit: "Regular",
            imageUrl: "https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=500&auto=format&fit=crop&q=60",
            ratings: 4.5,
            numReviews: 145
        },
        {
            name: "Flying Machine Cargo Pants",
            description: "Multi-pocket rugged cargos.",
            gender: "Men",
            category: "Trousers",
            brand: "Flying Machine",
            price: 1899,
            discount: 40,
            stock: 35,
            sizes: ["30", "32", "34"],
            colors: ["Camouflage", "Olive"],
            fabric: "Cotton",
            fit: "Relaxed",
            imageUrl: "https://images.unsplash.com/photo-1517445312882-bc9910d016b7?w=500&auto=format&fit=crop&q=60",
            ratings: 4.4,
            numReviews: 210
        },
        {
            name: "Columbia Winter Jacket",
            description: "Water-resistant insulated jacket.",
            gender: "Men",
            category: "Jackets",
            brand: "Columbia",
            price: 6999,
            discount: 10,
            stock: 12,
            sizes: ["M", "L", "XL"],
            colors: ["Black"],
            fabric: "Nylon",
            fit: "Regular",
            imageUrl: "https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=500&auto=format&fit=crop&q=60",
            ratings: 4.9,
            numReviews: 45
        },
        {
            name: "H&M Puffer Jacket",
            description: "Warm quilted puffer jacket.",
            gender: "Men",
            category: "Jackets",
            brand: "H&M",
            price: 3999,
            discount: 20,
            stock: 22,
            sizes: ["S", "M", "L"],
            colors: ["Mustard", "Black"],
            fabric: "Polyester",
            fit: "Regular",
            imageUrl: "https://images.unsplash.com/photo-1544923246-77307dd654cb?w=500&auto=format&fit=crop&q=60",
            ratings: 4.6,
            numReviews: 134
        },
        {
            name: "Puma Track Jacket",
            description: "Zip-up sporty track jacket.",
            gender: "Men",
            category: "Jackets",
            brand: "Puma",
            price: 2499,
            discount: 30,
            stock: 28,
            sizes: ["M", "L", "XL"],
            colors: ["Navy Blue", "White"],
            fabric: "Polyester",
            fit: "Slim",
            imageUrl: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=500&auto=format&fit=crop&q=60",
            ratings: 4.7,
            numReviews: 176
        },
        {
            name: "Wildcraft Windcheater",
            description: "Lightweight windproof jacket.",
            gender: "Men",
            category: "Jackets",
            brand: "Wildcraft",
            price: 1999,
            discount: 15,
            stock: 45,
            sizes: ["S", "M", "L", "XL"],
            colors: ["Neon Orange", "Grey"],
            fabric: "Nylon",
            fit: "Regular",
            imageUrl: "https://images.unsplash.com/photo-1509551388413-e18d0ac5d495?w=500&auto=format&fit=crop&q=60",
            ratings: 4.5,
            numReviews: 220
        },
        {
            name: "Woodland Fleece Sweater",
            description: "Outdoor thermal fleece sweater.",
            gender: "Men",
            category: "Sweaters",
            brand: "Woodland",
            price: 3499,
            discount: 25,
            stock: 15,
            sizes: ["L", "XL", "XXL"],
            colors: ["Brown"],
            fabric: "Fleece",
            fit: "Relaxed",
            imageUrl: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=500&auto=format&fit=crop&q=60",
            ratings: 4.8,
            numReviews: 67
        },
        {
            name: "Vero Moda Crop Top",
            description: "Trendy ribbed crop top.",
            gender: "Women",
            category: "Tops",
            brand: "Vero Moda",
            price: 999,
            discount: 30,
            stock: 50,
            sizes: ["XS", "S", "M", "L"],
            colors: ["White", "Lavender"],
            fabric: "Cotton Blend",
            fit: "Slim",
            imageUrl: "https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=500&auto=format&fit=crop&q=60",
            ratings: 4.6,
            numReviews: 312
        },
        {
            name: "Forever 21 Tank Top",
            description: "Basic casual tank top.",
            gender: "Women",
            category: "Tops",
            brand: "Forever 21",
            price: 599,
            discount: 10,
            stock: 80,
            sizes: ["S", "M", "L"],
            colors: ["Black", "Grey"],
            fabric: "Cotton",
            fit: "Regular",
            imageUrl: "/images/women/f21_top1.jpg",
            imageUrl: "https://images.unsplash.com/photo-1503342394128-c104d54dba01?w=500&auto=format&fit=crop&q=60",
            ratings: 4.4,
            numReviews: 405
        },
        {
            name: "Mango Blouse",
            description: "Elegant chiffon evening blouse.",
            gender: "Women",
            category: "Tops",
            brand: "Mango",
            price: 2299,
            discount: 25,
            stock: 25,
            sizes: ["S", "M", "L", "XL"],
            colors: ["Maroon"],
            fabric: "Chiffon",
            fit: "Regular",
            imageUrl: "https://images.unsplash.com/photo-1564257631407-4deb1f99d992?w=500&auto=format&fit=crop&q=60",
            ratings: 4.8,
            numReviews: 124
        },
        {
            name: "Zara Ruffled Top",
            description: "Stylish top with ruffle details.",
            gender: "Women",
            category: "Tops",
            brand: "Zara",
            price: 1999,
            discount: 15,
            stock: 30,
            sizes: ["XS", "S", "M"],
            colors: ["White"],
            fabric: "Polyester",
            fit: "Relaxed",
            imageUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=60",
            ratings: 4.7,
            numReviews: 189
        },
        {
            name: "H&M Ribbed Top",
            description: "Long sleeve ribbed knit top.",
            gender: "Women",
            category: "Tops",
            brand: "H&M",
            price: 1299,
            discount: 20,
            stock: 45,
            sizes: ["S", "M", "L"],
            colors: ["Beige", "Olive"],
            fabric: "Knit",
            fit: "Slim",
            imageUrl: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=500&auto=format&fit=crop&q=60",
            ratings: 4.5,
            numReviews: 215
        },
        {
            name: "W A-Line Kurta",
            description: "Embroidered ethnic A-line kurta.",
            gender: "Women",
            category: "Kurtis",
            brand: "W",
            price: 1999,
            discount: 40,
            stock: 35,
            sizes: ["S", "M", "L", "XL", "XXL"],
            colors: ["Teal"],
            fabric: "Cotton",
            fit: "Regular",
            imageUrl: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=500&auto=format&fit=crop&q=60",
            ratings: 4.6,
            numReviews: 145
        },
        {
            name: "Aurelia Solid Kurti",
            description: "Simple everyday wear kurti.",
            gender: "Women",
            category: "Kurtis",
            brand: "Aurelia",
            price: 899,
            discount: 30,
            stock: 60,
            sizes: ["S", "M", "L", "XL"],
            colors: ["Pink", "Yellow"],
            fabric: "Rayon",
            fit: "Straight",
            imageUrl: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=500&auto=format&fit=crop&q=60",
            ratings: 4.4,
            numReviews: 278
        },
        {
            name: "FabIndia Silk Saree",
            description: "Handwoven pure silk saree.",
            gender: "Women",
            category: "Sarees",
            brand: "FabIndia",
            price: 5999,
            discount: 10,
            stock: 10,
            sizes: ["Free Size"],
            colors: ["Emerald Green"],
            fabric: "Silk",
            fit: "Regular",
            imageUrl: "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=500&auto=format&fit=crop&q=60",
            ratings: 4.9,
            numReviews: 42
        },
        {
            name: "Nalli Kanchipuram Saree",
            description: "Traditional Kanchipuram silk saree.",
            gender: "Women",
            category: "Sarees",
            brand: "Nalli",
            price: 8499,
            discount: 5,
            stock: 8,
            sizes: ["Free Size"],
            colors: ["Red", "Gold"],
            fabric: "Silk",
            fit: "Regular",
            imageUrl: "https://images.unsplash.com/photo-1609357605129-26f69add5d6e?w=500&auto=format&fit=crop&q=60",
            ratings: 5.0,
            numReviews: 31
        },
        {
            name: "Soch Anarkali Suit",
            description: "Festive wear Anarkali suit set.",
            gender: "Women",
            category: "Kurtis",
            brand: "Soch",
            price: 3999,
            discount: 25,
            stock: 18,
            sizes: ["M", "L", "XL"],
            colors: ["Navy Blue"],
            fabric: "Georgette",
            fit: "Regular",
            imageUrl: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=500&auto=format&fit=crop&q=60",
            ratings: 4.7,
            numReviews: 89
        },
        {
            name: "Mango Maxi Dress",
            description: "Flowy summer maxi dress.",
            gender: "Women",
            category: "Dresses",
            brand: "Mango",
            price: 3499,
            discount: 30,
            stock: 20,
            sizes: ["S", "M", "L"],
            colors: ["Floral Print"],
            fabric: "Viscose",
            fit: "Relaxed",
            imageUrl: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=500&auto=format&fit=crop&q=60",
            ratings: 4.6,
            numReviews: 156
        },
        {
            name: "Forever New Party Dress",
            description: "Sequined cocktail dress.",
            gender: "Women",
            category: "Dresses",
            brand: "Forever New",
            price: 4999,
            discount: 15,
            stock: 15,
            sizes: ["6", "8", "10", "12"],
            colors: ["Rose Gold"],
            fabric: "Polyester",
            fit: "Slim",
            imageUrl: "https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=500&auto=format&fit=crop&q=60",
            ratings: 4.8,
            numReviews: 112
        },
        {
            name: "Allen Solly Shift Dress",
            description: "Professional knee-length dress.",
            gender: "Women",
            category: "Dresses",
            brand: "Allen Solly",
            price: 2199,
            discount: 20,
            stock: 25,
            sizes: ["S", "M", "L", "XL"],
            colors: ["Navy Blue"],
            fabric: "Poly Viscose",
            fit: "Regular",
            imageUrl: "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=500&auto=format&fit=crop&q=60",
            ratings: 4.5,
            numReviews: 88
        },
        {
            name: "Marks & Spencer Pencil Skirt",
            description: "Tailored formal pencil skirt.",
            gender: "Women",
            category: "Skirts",
            brand: "Marks & Spencer",
            price: 1899,
            discount: 25,
            stock: 30,
            sizes: ["8", "10", "12", "14"],
            colors: ["Black"],
            fabric: "Polyester Blend",
            fit: "Slim",
            imageUrl: "https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=500&auto=format&fit=crop&q=60",
            ratings: 4.7,
            numReviews: 67
        },
        {
            name: "ONLY A-Line Skirt",
            description: "Casual denim A-line skirt.",
            gender: "Women",
            category: "Skirts",
            brand: "ONLY",
            price: 1499,
            discount: 40,
            stock: 35,
            sizes: ["26", "28", "30", "32"],
            colors: ["Light Blue Wash"],
            fabric: "Denim",
            fit: "Regular",
            imageUrl: "https://images.unsplash.com/photo-1582142306909-195724d33ffc?w=500&auto=format&fit=crop&q=60",
            ratings: 4.4,
            numReviews: 134
        },
        {
            name: "Nike Yoga Pants",
            description: "High-waist stretch yoga leggings.",
            gender: "Women",
            category: "Activewear",
            brand: "Nike",
            price: 2499,
            discount: 15,
            stock: 45,
            sizes: ["XS", "S", "M", "L"],
            colors: ["Black", "Grey"],
            fabric: "Spandex",
            fit: "Skinny",
            imageUrl: "https://images.unsplash.com/photo-1506634572416-48cdfe530110?w=500&auto=format&fit=crop&q=60",
            ratings: 4.9,
            numReviews: 412
        },
        {
            name: "Adidas Sports Bra",
            description: "High-impact training sports bra.",
            gender: "Women",
            category: "Activewear",
            brand: "Adidas",
            price: 1799,
            discount: 20,
            stock: 50,
            sizes: ["S", "M", "L"],
            colors: ["White", "Black"],
            fabric: "Polyester Elastane",
            fit: "Slim",
            imageUrl: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=500&auto=format&fit=crop&q=60",
            ratings: 4.8,
            numReviews: 289
        },
        {
            name: "Levi's Bootcut Jeans",
            description: "Classic retro bootcut jeans.",
            gender: "Women",
            category: "Jeans",
            brand: "Levi's",
            price: 2799,
            discount: 10,
            stock: 22,
            sizes: ["26", "28", "30", "32"],
            colors: ["Dark Blue"],
            fabric: "Denim",
            fit: "Bootcut",
            imageUrl: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=500&auto=format&fit=crop&q=60",
            ratings: 4.6,
            numReviews: 176
        },
        {
            name: "Kraken High-Waist Jeans",
            description: "Trendy distressed high-waist jeans.",
            gender: "Women",
            category: "Jeans",
            brand: "Kraken",
            price: 1999,
            discount: 35,
            stock: 40,
            sizes: ["28", "30", "32", "34"],
            colors: ["Ice Blue"],
            fabric: "Denim",
            fit: "Skinny",
            imageUrl: "https://images.unsplash.com/photo-1582418702059-97ebafb35d09?w=500&auto=format&fit=crop&q=60",
            ratings: 4.3,
            numReviews: 245
        },
        {
            name: "Biba Palazzo Pants",
            description: "Flared ethnic palazzo pants.",
            gender: "Women",
            category: "Trousers",
            brand: "Biba",
            price: 1199,
            discount: 30,
            stock: 55,
            sizes: ["S", "M", "L", "XL"],
            colors: ["Off White", "Black"],
            fabric: "Rayon",
            fit: "Relaxed",
            imageUrl: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=500&auto=format&fit=crop&q=60",
            ratings: 4.7,
            numReviews: 310
        },
        {
            name: "Puma Graphic Hoodie",
            description: "Casual everyday sports hoodie.",
            gender: "Women",
            category: "Hoodies",
            brand: "Puma",
            price: 2199,
            discount: 20,
            stock: 30,
            sizes: ["S", "M", "L", "XL"],
            colors: ["Pink", "Grey"],
            fabric: "Fleece",
            fit: "Relaxed",
            imageUrl: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=500&auto=format&fit=crop&q=60",
            ratings: 4.6,
            numReviews: 142
        }
    ];

    await Product.insertMany(products);
    
    console.log('✅ Data Imported Successfully!');
    await mongoose.connection.close();
    process.exit(0);
  } catch (error) {
    console.error(`❌ Error with data import: ${error.message}`);
    await mongoose.connection.close();
    process.exit(1);
  }
};

importData();